### ISSUE TITLE
Stopping upon start up

### ISSUE THREAD

**Issue by HeymineVtwo** [PixelGuy123/New-Baldis-Basics-Times#1]
https://github.com/user-attachments/assets/665044ec-a33d-498f-84cb-f85435d30b77
i did everything correct?

**Comment by PixelGuy123** [comment]
To freeze at Npc creation, you must've having the PixelInternalAPI outdated. Make sure Times and EditorCustomRooms are also updated.

**Comment by HeymineVtwo** [comment]
Thank you so much!

**Comment by HeymineVtwo** [comment]
> To freeze at Npc creation, you must've having the PixelInternalAPI outdated. Make sure Times and EditorCustomRooms are also updated.

Thank you so much!
